# Generated by Django 5.2.16 on 2026-07-10 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehmat_app', '0002_seed_achievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True)),
                ('source_path', models.CharField(blank=True, db_index=True, help_text='Folder path relative to the import root (natural key).', max_length=1000, null=True, unique=True)),
                ('ordering', models.IntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('ordering', 'name'),
            },
        ),
        migrations.RenameIndex(
            model_name='material',
            new_name='mehmat_app__categor_e5b66a_idx',
            old_name='mehmat_app__categor_495bfe_idx',
        ),
        migrations.RemoveField(
            model_name='material',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/files/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='material',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('presentation', 'Presentation'), ('document', 'Document'), ('spreadsheet', 'Spreadsheet'), ('image', 'Image'), ('audio', 'Audio'), ('archive', 'Archive'), ('link', 'Link'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='material',
            name='source_path',
            field=models.CharField(blank=True, db_index=True, help_text='File path relative to the import root (natural key).', max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.CharField(choices=[('algebra', 'Algebra'), ('geometry', 'Geometry'), ('functions', 'Functions'), ('derivatives', 'Derivatives'), ('probability', 'Probability'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mehmat_app.category'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='mehmat_app.category'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['file_type', 'is_published'], name='mehmat_app__file_ty_86c27b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_published'], name='mehmat_app__parent__1f312f_idx'),
        ),
    ]
