# Generated by Django 5.2.16 on 2026-07-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehmat_app', '0004_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='matching',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submissionanswer',
            name='matching_answer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submissionanswer',
            name='text_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single choice'), ('multiple', 'Multiple choice'), ('ordering', 'Ordering'), ('short_answer', 'Short answer'), ('matching', 'Matching')], default='single', max_length=20),
        ),
    ]
